// API Configuration
// Auto-generated by deploy script - DO NOT EDIT MANUALLY

const CONFIG = {
    // Backend API URL - Ngrok URL for Backend (Go server on port 8080)
    API_BASE_URL: window.location.hostname === 'localhost' 
        ? 'http://localhost:8080'
        : 'https://kristen-uncontradictive-nery.ngrok-free.dev',
    
    // ML Service URL - Ngrok URL for ML Service (Python Flask on port 5001)
    ML_BASE_URL: window.location.hostname === 'localhost'
        ? 'http://localhost:5001'
        : 'https://kristen-uncontradictive-nery.ngrok-free.dev',
    
    // API Endpoints
    ENDPOINTS: {
        PREDICT: '/api/predict',
        SIMILARITY: '/api/similarity',
        ALIGN: '/api/align',
        PROTEINS: '/api/proteins',
        HEALTH: '/health'
    }
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}
