// API Configuration
// Auto-generated by deploy script - DO NOT EDIT MANUALLY

const CONFIG = {
    // Backend API URL - All requests go through Backend
    // Backend will proxy ML service requests internally
    API_BASE_URL: window.location.hostname === 'localhost' 
        ? 'http://localhost:8080'
        : 'https://kristen-uncontradictive-nery.ngrok-free.dev',
    
    // API Endpoints (Backend routes these to ML service as needed)
    ENDPOINTS: {
        PREDICT: '/api/predict',
        SIMILARITY: '/api/similarity',
        ALIGN: '/api/align',
        PROTEINS: '/api/proteins',
        HEALTH: '/health'
    }
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}
